services:
  postgres:
    container_name: projetoteca_db
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=projetoteca
    volumes:
      - projetoteca_pg_data:/bitnami/postgresql

volumes:
  projetoteca_pg_data: